AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: "Role to run EKS Cluster in Datadog and Hashicorp Workshop"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        - "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
      Policies: 
        - PolicyName: deny_cloudwatch_log_groups
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Deny
                Action: 'logs:CreateLogGroup'
                Resource: 'arn:aws:logs:eu-west-1:*:log-group:/aws/eks/datadog-webminar/cluster'
      RoleName: "EKS_Service_Role_CF"
